fullnameOverride: example-base
image:
  repository: nginx
  tag: latest
services:
  - name: service_name1
    type: NodePort
    annotations:
      - name: annot
        value: val
    ports:
     - name: port_name1
       port: 8080
       targetPort: 8080
     - name: port_name2
       port: 8090
       targetPort: 8090
serviceAccount:
  create: true
autoscaling:
  enabled: true