{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miso-deployment.fullname" . }}
  labels:
    {{- include "miso-deployment.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- if .Values.service.additionalPorts }}
  {{ toYaml .Values.service.additionalPorts | indent 4 }}
  {{- end }}
  selector:
    {{- include "miso-deployment.selectorLabels" . | nindent 4 }}
{{- end }}