{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- if .Values.service.additionalPorts }}
  {{ toYaml .Values.service.additionalPorts | indent 4 }}
  {{- end }}
  selector:
    app: {{ include "deployment.fullname" . }}
{{- end }}
{{- range $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name | quote }}
  labels:
    {{- include "deployment.labels" $ | nindent 4 }}
  annotations:
    {{- range $annotation := $service.annotations }}
    {{ $annotation.name }}: {{ $annotation.value }}
    {{- end }}
spec:
  type: {{ $service.type }}
  selector:
    app: {{ include "deployment.fullname" $ }}
  ports:
    {{- range $port := $service.ports }}
    - protocol: TCP
      port: {{ $port.port }}
      name: {{ $port.name | quote }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
{{- end }}