fullnameOverride: example-statefulset
image:
  repository: nginx
  tag: latest
volumeMounts:
  - name: name1
    mountPath: mount_path_1
  - name: name2
    mountPath: mount_path_2
volumeClaimTemplates:
  - name: temp1
    accessModes: ["ReadWriteOnce"]
    requestedStorage: 15Gi
resources:
  production:
    limits:
      cpu: "0.7"
      memory: 900Mi
    requests:
      cpu: "0.5"
      memory: 700Mi
